import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    padding: 40,
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#111827',
    paddingBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#111827',
  },
  shopInfo: {
    fontSize: 10,
    color: '#4B5563',
    textAlign: 'right',
  },
  section: {
    margin: 10,
    padding: 10,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 10,
    backgroundColor: '#F3F4F6',
    padding: 5,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 5,
  },
  label: {
    fontSize: 10,
    color: '#6B7280',
    width: '40%',
  },
  value: {
    fontSize: 10,
    color: '#111827',
    width: '60%',
    fontWeight: 'bold',
  },
  footer: {
    position: 'absolute',
    bottom: 40,
    left: 40,
    right: 40,
    fontSize: 8,
    color: '#9CA3AF',
    textAlign: 'center',
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    paddingTop: 10,
  },
  amountBox: {
    marginTop: 20,
    backgroundColor: '#F3F4F6',
    padding: 20,
    alignItems: 'center',
    borderRadius: 5,
  },
  amountText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#111827',
  }
});

export const PaymentReceiptPDF = ({ payment, loan, customer, shop }: any) => (
  <Document>
    <Page size="A5" style={styles.page}>
      
      {/* Header */}
      <View style={styles.header}>
        <View>
          <Text style={styles.title}>PAYMENT RECEIPT</Text>
          <Text style={{ fontSize: 10, color: '#6B7280', marginTop: 5 }}>Receipt Date: {new Date(payment?.payment_date).toLocaleDateString()}</Text>
        </View>
        <View style={styles.shopInfo}>
          <Text style={{ fontSize: 14, fontWeight: 'bold', color: '#111827' }}>{shop?.shop_name || "Suvarna Jewellery"}</Text>
          <Text>Owner: {shop?.owner_name || "Owner"}</Text>
          <Text>Mobile: {shop?.mobile || "N/A"}</Text>
        </View>
      </View>

      {/* Customer & Loan Details */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>RECEIVED FROM</Text>
        <View style={styles.row}>
          <Text style={styles.label}>Customer Name:</Text>
          <Text style={styles.value}>{customer?.full_name}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Against Loan Number:</Text>
          <Text style={styles.value}>{loan?.loan_number}</Text>
        </View>
      </View>

      {/* Payment Details */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>PAYMENT DETAILS</Text>
        <View style={styles.row}>
          <Text style={styles.label}>Payment Type:</Text>
          <Text style={styles.value}>{payment?.payment_type}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Payment Method:</Text>
          <Text style={styles.value}>{payment?.payment_method}</Text>
        </View>
        {payment?.notes && (
          <View style={styles.row}>
            <Text style={styles.label}>Notes:</Text>
            <Text style={styles.value}>{payment?.notes}</Text>
          </View>
        )}
      </View>

      <View style={styles.amountBox}>
        <Text style={{ fontSize: 12, color: '#6B7280', marginBottom: 5 }}>Amount Received</Text>
        <Text style={styles.amountText}>Rs. {Number(payment?.amount).toLocaleString('en-IN')}</Text>
      </View>

      {/* Footer */}
      <Text style={styles.footer} fixed>
        Generated by SuvarnaLoan ERP • This is a computer-generated receipt.
      </Text>
    </Page>
  </Document>
);
